### ISSUE TITLE
Can you share the code you used to generate tfrecord from your dataSetToolVideo?

### ISSUE THREAD

**Issue by denton0131** [musikisomorphie/swd#3]
Hi,

I am wondering if you can share your main function to use the object you have implemented inside the dataSetToolVideo.py?  It will be great if we can use your code for testing and try.

Many thanks,
Jonny

**Comment by musikisomorphie** [comment]
Hi, I don't have that part of code anymore. Due to legal issue, we are not able to release the collected training data, so we didn't upload the code of processing training data. Basically, we follow the implementation of https://github.com/tkarras/progressive_growing_of_gans/blob/master/dataset_tool.py . You could get some inspiration from it. Sorry for the inconvenience.

**Comment by zhiwu-huang** [comment]
Hi, we previously created the tfrecords data from hdf5 data using the following command: 
python dataset_tool_video.py create_from_hdf5 /tfrecord_path /hdf5_path, where the code "dataset_tool_video.py" has been released at the repository.
